### ISSUE TITLE
Customize the section dataviz

### ISSUE THREAD

**Issue by ambarja** [nucleic-acid/jollydatablog#1]
Hi @nucleic-acid, I have recently migrated my entire website to Quarto and I have seen your website and would like to set up the dataviz section in the same way. Your website was an inspiration for me.
Best regards.
Antony
Thanks

**Comment by nucleic-acid** [comment]
Hi @ambarja! So glad to hear this! If you have questions regarding the code I used for that, please let me know. I'll also publish the repository of the current website, as soon as I have ported all the posts over from distill.

**Comment by ambarja** [comment]
> Hi @ambarja! So glad to hear this! If you have questions regarding the code I used for that, please let me know. I'll also publish the repository of the current website, as soon as I have ported all the posts over from distill.

Thank you very much for your quick reply, my question is about the `yaml` configuration of the **dataviz** section.
I would like to have the same configuration.

![Captura de pantalla de 2022-09-17 15-17-31](https://user-images.githubusercontent.com/23284899/190875047-3736264c-d58f-4497-816b-0bfaa01f09bc.png)
![Captura de pantalla de 2022-09-17 15-17-06](https://user-images.githubusercontent.com/23284899/190875033-a521da39-9bb1-41dd-ab6c-fc1f7dba0e98.png)

**Comment by nucleic-acid** [comment]
So this is the complete `challenges.qmd` file including the YAML:

```
---
title: "data viz gallery"
subtitle: |
  A collection of datavisualizations created for challenges such as #TidyTuesday or the #30DayChartChallenge. Others resulted from personal data exploration projects found on this blog. The code can either be found in blog posts or on my github page.
page-layout: full
code-tools: false
---

::: {.column-screen}
    ```{r}
    #| echo: false
    library(pixture)
    
    pixgallery(
      list.files("assets/challenges_images", 
                 full.names=TRUE),
      dim="350px",
      gap = "10px"
    )
    
    ```
:::

## Comments
Do you like the visualizations? Seen anything you want to discuss? Leave a comment, I'd be happy to hear it!
```


There's a short explanation on the pixture package here:
https://jollydata.blog/posts/2022-08-06-_switching-to-quarto/switching-to-quarto.html#data-viz-gallery

**Comment by ambarja** [comment]
It's amazing the powerful of Quarto with integration R, thank very much.
